export function generateAiMasterPrompt(): string {
  return [
    "# MASTER AI GENERATION PROMPT (.XLSM SPECIFICATION)",
    "# PARAMOUNT STATIONERY & CLEANING ITEMS PROCUREMENT & INVENTORY CONTROL SYSTEM",
    "",
    "Copy and paste the entire prompt below into ChatGPT, Claude, Gemini, or GitHub Copilot to generate 100% of the complete Macro-Enabled Excel VBA Procurement & Inventory Control System from scratch:",
    "",
    "================================================================================",
    "START OF AI GENERATION PROMPT",
    "================================================================================",
    "",
    "You are an elite 32-Bit / 64-Bit Excel VBA developer, Office Automation engineer, and UX/UI designer specializing in enterprise inventory management systems, UserForm interface design, local directory file management, stock count discrepancy reconciliation, data security, and automated PDF voucher rendering using `ExportAsFixedFormat`.",
    "",
    "I need you to generate a complete, production-ready, macro-enabled **Excel Procurement & Inventory Control System Workbook (`Stationery_&_Cleaning_System.xlsm`)** for managing stationery, cleaning supplies, and general inventory items. Provide 100% complete, syntactically valid VBA code for all modules, forms, and workbook events, along with exact instructions for assembling the worksheets, UserForms, buttons, icons, PDF issue slip & adjustment voucher generation, auto-creating output directories, item deletion on preview confirmation, and locking the project. Do NOT include any email sending code or email setup—focus purely on generating and saving formatted PDF vouchers locally and enforcing strict role-based access control.",
    "",
    "---",
    "",
    "### 1. SYSTEM IDENTITY, RUNTIME ARCHITECTURE & MASTER DIRECTORIES",
    "- **Workbook Name**: `Stationery_&_Cleaning_System.xlsm`",
    "- **Format**: Excel Macro-Enabled Workbook (FileFormat 52 / `xlOpenXMLWorkbookMacroEnabled`).",
    "- **Compatibility**: 32-Bit and 64-Bit Microsoft Excel (Office 2013, 2016, 2019, 2021, and Microsoft 365) utilizing `PtrSafe` and `LongPtr` API declarations.",
    "- **Master Folder Hierarchy & Data Storage Architecture**:",
    "  - Root Directory: `C:\\Stationery & Cleaning\\` (or user-configurable master directory path).",
    "  - Subfolder 1: `Issued_Items\\` (Stores generated departmental Requisition Issue Slips in PDF format).",
    "  - Subfolder 2: `Received_Items\\` (Stores generated Goods Received Note / GRN Delivery Vouchers in PDF format).",
    "  - Subfolder 3: `Adjustments\\` (Stores generated Physical Stock Count Reconciliation & Discrepancy Vouchers in PDF format).",
    "  - **Security & Directory Access Policy**:",
    "    - Superior Admin (`ADM001` - Rachel Pickard) is the ONLY authorized user who can access and configure the master storage directory paths.",
    "    - Standard users cannot access, alter, or browse the underlying file system folders directly from the interface.",
    "    - Standard users have read-only access to view and reprint generated PDF vouchers by clicking on corresponding records in the `Movement_Log` worksheet.",
    "  - Automated Directory Check: VBA routines must call `EnsureDirectoriesExist()` before saving any document to create missing folders using `Dir()` and `MkDir`.",
    "",
    "---",
    "",
    "### 2. UI/UX DESIGN SYSTEM, THEME ENGINE & TYPOGRAPHY GUIDELINES",
    "The workbook implements an enterprise-grade design system with WCAG AA compliance (minimum 4.5:1 text-to-background contrast, up to 18:1 in high-contrast cards) and dual-theme switching capability:",
    "",
    "#### A. Color Palette & VBA RGB Constants (`mod_ThemeEngine.bas`):",
    "- **Light Theme (Professional Modern Office)**:",
    "  - Canvas Background: Slate 50 (`RGB(248, 250, 252)` / `#F8FAFC`)",
    "  - Surface Cards / Panels: Pure White (`RGB(255, 255, 255)` / `#FFFFFF`)",
    "  - Primary Text: Deep Slate 900 (`RGB(15, 23, 42)` / `#0F172A`) — 16.8:1 contrast",
    "  - Secondary / Muted Text: Slate 600 (`RGB(71, 85, 105)` / `#475569`) — 5.4:1 contrast",
    "  - Brand Accent: Deep Teal 600 (`RGB(13, 148, 136)` / `#0D9488`)",
    "  - Success: Emerald 600 (`RGB(22, 163, 74)` / `#16A34A`)",
    "  - Warning / Alert: Amber 600 (`RGB(217, 119, 6)` / `#D97706`)",
    "  - Danger: Red 600 (`RGB(220, 38, 38)` / `#DC2626`)",
    "  - Borders: Slate 200 (`RGB(226, 232, 240)` / `#E2E8F0`)",
    "",
    "- **Dark Theme (Deep Slate Terminal)**:",
    "  - Canvas Background: Slate 950 (`RGB(2, 6, 23)` / `#020617`)",
    "  - Surface Cards / Panels: Slate 900 (`RGB(15, 23, 42)` / `#0F172A`)",
    "  - Primary Text: Slate 50 (`RGB(248, 250, 252)` / `#F8FAFC`) — 18.2:1 contrast",
    "  - Secondary / Muted Text: Slate 400 (`RGB(148, 163, 184)` / `#94A3B8`) — 5.8:1 contrast",
    "  - Brand Accent: Teal 400 (`RGB(45, 212, 191)` / `#2DD4BF`)",
    "  - Success: Emerald 400 (`RGB(74, 222, 128)` / `#4ADE80`)",
    "  - Warning: Amber 400 (`RGB(251, 191, 36)` / `#FBBF24`)",
    "  - Danger: Red 400 (`RGB(248, 113, 113)` / `#F87171`)",
    "  - Borders: Slate 800 (`RGB(30, 41, 59)` / `#1E293B`)",
    "",
    "#### B. Typography & Grid Hierarchy:",
    "- Font Family: `Segoe UI` (Windows standard) with `Aptos` or `Calibri` fallback.",
    "- Item IDs, Document Codes, and Timestamps: Monospace `Consolas`.",
    "- Size Hierarchy: Section Titles: 16-18pt Bold; Table Headers: 11pt Bold with uppercase tracking; Grid Data Cells: 10pt Regular; Badges & Sub-labels: 9pt Medium.",
    "- Row Heights & Column Polish:",
    "  - Header Rows: 26pt; Data Rows: 20pt; Empty divider rows: 10pt.",
    "  - Alignment: Item IDs, Codes & Dates centered; Text descriptions left-aligned with 4pt cell padding; Quantities & balances right-aligned; Status badges centered.",
    "  - Frozen Panes: Freeze panes at Row 2 so header row remains fixed during vertical scrolling.",
    "  - Gridlines: Subtle, visible gridlines with soft borders.",
    "",
    "#### C. Official Organization Brand Logo Integration:",
    "- Asset Name: `PEX Green (2).png`",
    "- Placement: Attached unaltered as-is at the top-left corner of the header banner on all generated PDF vouchers (height: 28mm, width: 16mm).",
    "- Visual Identity: Dark graphite textured card (`#24282D`), lime-green (`#C6D92C` / `RGB(198, 217, 44)`) striding worker with hardhat, and vertical lowercase `paramount` brand lettering.",
    "",
    "---",
    "",
    "### 3. STARTUP, AUTHENTICATION & ROLE-BASED ACCESS CONTROL (RBAC)",
    "- **ZERO AUTOMATIC LOGINS**: Upon opening the workbook, no user account is logged in automatically.",
    "- **WORKBOOK_OPEN EVENT ROUTINE (`ThisWorkbook.cls`)**:",
    "  1. Session reset: Initialize global variables (`g_CurrentIssuerID = \"\"`, `g_CurrentIssuerName = \"\"`, `g_CurrentIssuerRole = \"\"`, `g_IsAuthenticated = False`).",
    "  2. Security lockdown: Ensure sheet `Admin_Config` is set to `xlSheetVeryHidden`.",
    "  3. Directory validation: Call `EnsureDirectoriesExist()` to guarantee `Issued_Items\\`, `Received_Items\\`, and `Adjustments\\` folders are ready.",
    "  4. Active View: Set active worksheet to `Master_Stock`.",
    "  5. Welcome Login Modal: Automatically trigger `frmLogin.Show` modal to prompt the user for authentication.",
    "- **LOGIN FORM REQUIREMENTS (`frmLogin`)**:",
    "  - `cmbQuickUsers`: Dropdown list populated with authorized staff accounts for convenient selection.",
    "  - `txtWorkID`: Work ID input (e.g., `ADM001`).",
    "  - `txtPassword`: Secret password input masked with `PasswordChar = \"*\"`. Passwords MUST NEVER be pre-filled or displayed in plain text.",
    "  - Max 3 failed attempts lockout before disabling input.",
    "  - On valid authentication against `Admin_Config` Table 1 (A:D):",
    "    - Assign global session state (`g_CurrentIssuerID`, `g_CurrentIssuerName`, `g_CurrentIssuerRole`, `g_IsAuthenticated = True`).",
    "    - Open `frmNavigation` switchboard dialog with a personalized greeting card.",
    "    - Set active worksheet to `Master_Stock`.",
    "",
    "---",
    "",
    "### 4. COMPLETE WORKSHEET SCHEMAS & AUDIT STRUCTURE",
    "The workbook (`Stationery_&_Cleaning_System.xlsm`) consists of exactly three dedicated worksheets:",
    "",
    "#### Sheet 1: `Master_Stock` (Live Inventory Control)",
    "- **Column A**: `ItemID` (Unique Code: `ST-001`... for Stationery, `CL-101`... for Cleaning, `GN-201`... for General)",
    "- **Column B**: `ItemName` (Full item description, e.g., 'A4 Copy Paper (500 sheets/ream)', 'Multi-Surface Disinfectant Cleaner (5L)')",
    "- **Column C**: `Category` (Exactly 3 categories: 'Stationery', 'Cleaning', or 'General')",
    "- **Column D**: `Qty` (Numeric integer representing available in-stock physical inventory)",
    "- **Column E**: `ReorderLevel` (Numeric minimum threshold for low-stock warnings)",
    "- **Column F**: `Unit` (Packaging unit: Reams, Boxes, Packs, Units, Containers, Drums, Rolls, Bottles, Cans, Kits)",
    "- **Dynamic Multi-Token Search & Indexing Engine**:",
    "  - Multi-field substring search indexing across Item Code, Item Name, Category, and Unit.",
    "  - Category filter dropdown / pills ('All Categories', 'Stationery', 'Cleaning', 'General', 'Low Stock Only').",
    "- **Top Quick Action Macro Ribbon Buttons**:",
    "  1. `btnOpenLogin` — Triggers `frmLogin` authentication dialog.",
    "  2. `btnOpenSwitchboard` — Opens `frmNavigation` main menu switchboard.",
    "  3. `btnEditDepartments` — Opens `frmDepartmentManager` to configure department heads and emails.",
    "  4. `btnCreateStock` — Opens `frmCreateStock` to register new inventory items.",
    "  5. `btnEditStock` — Opens `frmEditStockItem` to edit or rename existing stock items.",
    "  6. `btnGoodsReceived` — Opens `frmStockDelivery` to process stock delivery shipments (GRN).",
    "  7. `btnIssueOut` — Opens `frmIssueRequest` to create departmental requisition carts.",
    "  8. `btnStockAdjustment` — Opens `frmStockAdjustment` to record physical stock counts & reconcile discrepancies.",
    "  9. `btnManageUsers` (Gold Crown) — Opens `frmUserManagement` (Rachel Pickard `ADM001` Superior Admin only).",
    "  10. `btnToggleTheme` — Toggles workbook theme between Light and Dark modes via `mod_ThemeEngine.bas`.",
    "- **Conditional Formatting Rules**:",
    "  - Highlight row in Soft Amber/Red (`RGB(254, 242, 242)`) when `Qty <= ReorderLevel` (Low Stock Alert).",
    "  - Highlight row in Soft Emerald (`RGB(240, 253, 244)`) when `Qty > ReorderLevel` (Stock Sufficient).",
    "",
    "#### Sheet 2: `Movement_Log` (Strictly Read-Only Immutable Audit Trail)",
    "- **IMMUTABILITY ENFORCEMENT**:",
    "  - Standard users CANNOT add, edit, or delete rows in `Movement_Log` directly.",
    "  - All rows are automatically generated through verified VBA macro workflows (`DELIVERY`, `ISSUE`, `ADJUSTMENT`).",
    "  - Standard users can click any row to open and reprint the associated PDF voucher from the local storage repository.",
    "- **Column A**: `Timestamp` (Format: `YYYY-MM-DD HH:MM:SS`)",
    "- **Column B**: `Type` (`DELIVERY`, `ISSUE`, or `ADJUSTMENT`)",
    "- **Column C**: `DocumentRef` (Full document reference number & saved PDF filename)",
    "- **Column D**: `ItemID` (Unique Item Code)",
    "- **Column E**: `ItemName` (Full item description)",
    "- **Column F**: `Qty` (Transaction quantity: positive `+Qty` for delivery, integer for issue, variance delta `+Qty` or `-Qty` for adjustment)",
    "- **Column G**: `DeptID` (Department ID, `WAREHOUSE` for deliveries, or `AUDIT-ADJ` for adjustments)",
    "- **Column H**: `DeptName` (Department Name, `Central Warehouse Supply`, or Stock Count Discrepancy Reason)",
    "- **Column I**: `DeptHead` (Department Head Name or `N/A`)",
    "- **Column J**: `IssuerID` (Work ID of authorized issuer / auditor who executed the transaction)",
    "- **Column K**: `Status` (`Completed` / `Verified` / `Adjusted`)",
    "- **Interactive Audit Trail**: Double-clicking or selecting any row in `Movement_Log` triggers VBA `FollowHyperlink` to immediately open the generated PDF issue slip, GRN voucher, or Stock Adjustment voucher for viewing and reprinting.",
    "",
    "#### Sheet 3: `Admin_Config` (CONFIDENTIAL — SUPERIOR ADMIN ONLY)",
    "- **SECURITY RESTRICTIONS & VERY HIDDEN SHEET GUARD**:",
    "  - Default state is `xlSheetVeryHidden`.",
    "  - Made visible (`xlSheetVisible`) ONLY when Rachel Pickard (`ADM001` / Procurement Manager) signs in with password `Superior1234`.",
    "  - `Workbook_SheetActivate` event guards this worksheet: if any other user attempts to navigate to `Admin_Config`, VBA immediately redirects them back to `Master_Stock` with a security alert.",
    "- **Columns A to D — Authorized Staff Credentials Table**:",
    "  - Row 1 Headers: `IssuerID` | `IssuerName` | `Role` | `SecretPassword`",
    "  - Staff Accounts:",
    "    1. `ADM001` | Rachel Pickard | Procurement Manager | `Superior1234` (Superior Admin)",
    "    2. `ADM002` | Loveness Mawisire | Master Inventory Controller | `Micky1234Master`",
    "    3. `ADM003` | Lyda Gurupira | Inventory Controller | `Master1234`",
    "    4. `ADM004` | Caeser Joe | Procurement Supervisor | `Second1234`",
    "    5. `ADM005` | Farai Mandoreba | Procurement Assistant | `Procurement1234`",
    "    6. `ADM006` | Bianca Mpakairi | Administrator | `Admin1234!`",
    "    7. `ADM007` | Farai Peter | Procurement Assistant | `Assistant1234`",
    "- **Columns F to I — Department Directory Master Table**:",
    "  - Row 1 Headers: `DeptID` | `DeptName` | `DeptHeadName` | `DeptHeadEmail`",
    "  - Departments:",
    "    1. `DEPT-101` | Human Resources & Talent | Elena Rostova | `elena.rostova@company.com`",
    "    2. `DEPT-102` | Finance & Accounting | Robert Vance | `robert.vance@company.com`",
    "    3. `DEPT-103` | Information Technology | Marcus Thorne | `marcus.thorne@company.com`",
    "    4. `DEPT-104` | Operations & Logistics | Amanda Hayes | `amanda.hayes@company.com`",
    "    5. `DEPT-105` | Facilities & Sanitation | Carlos Mendez | `carlos.mendez@company.com`",
    "    6. `DEPT-106` | Sales & Marketing | Patricia Sterling | `patricia.sterling@company.com`",
    "",
    "---",
    "",
    "### 5. PHYSICAL STOCK COUNT ADJUSTMENT SPECIFICATION (DISCREPANCY HANDLING)",
    "To handle discrepancies between physical shelf counts and recorded system balances:",
    "1. **Discrepancy Identification**: Users conduct physical stock counts and enter the verified shelf quantity.",
    "2. **Real-Time Variance Calculation**: VBA automatically computes `Variance = Physical Count - System Recorded Quantity`.",
    "3. **Reason Code Categorization**:",
    "   - `COUNT_DISCREPANCY`: General stock count variance / recount correction.",
    "   - `DAMAGED`: Damaged or broken goods written off.",
    "   - `EXPIRED`: Expired or deteriorated cleaning supplies / chemical solutions.",
    "   - `THEFT`: Unaccounted shortage or suspected shrinkage.",
    "   - `FOUND_SURPLUS`: Unrecorded returned goods or unlogged delivery surplus.",
    "   - `SUPPLIER_SHORT`: Supplier shipment discrepancy identified post-receiving.",
    "4. **Audit Trail Logging & Voucher Generation**:",
    "   - Overwrites `Master_Stock` available quantity with the physical count.",
    "   - Appends a detailed `ADJUSTMENT` record into `Movement_Log` showing Delta Qty, Reason, Auditor, and Audit Ref.",
    "   - Automatically generates and exports a signed `Stock_Adjustment_ADJ-XXXXXX_YYYYMMDD_HHMMSS.pdf` voucher into `C:\\Stationery & Cleaning\\Adjustments\\`.",
    "",
    "---",
    "",
    "### 6. COMPLETE USERFORMS INVENTORY & INTERACTIVE WORKFLOWS",
    "Provide complete VBA code, control layout specifications, properties, and event handlers for all UserForms:",
    "",
    "#### 1. `frmLogin` (Authentication & Welcome Dialog)",
    "- Controls: `cmbQuickUsers`, `txtWorkID`, `txtPassword` (`PasswordChar = \"*\"`), `btnLogin`, `btnCancel`, `lblStatus`, `lblTitle`.",
    "- Logic: Validates input against `Admin_Config!A:D`. Max 3 attempts. On success: sets `g_IsAuthenticated = True`, stores session info, displays `frmNavigation`, and navigates to `Master_Stock`.",
    "",
    "#### 2. `frmNavigation` (Main Switchboard & Greeting Card)",
    "- Controls: `lblWelcome` (Shows active issuer name, ID, role, and login timestamp), `btnStockUpdate` (Stock Delivery), `btnIssueRequest` (Issue Items), `btnStockAdjustment` (Stock Adjustment), `btnCreateStock` (Create Stock), `btnEditStock` (Edit Stock), `btnManageDepts` (Departments), `btnMasterStock` (View Master Sheet), `btnManageUsers` (User Accounts - ADM001 only), `btnExit` (Close).",
    "- Logic: Serves as the central command hub. Clicking any button launches the corresponding form; clicking `btnMasterStock` closes the switchboard to inspect the sheet.",
    "",
    "#### 3. `frmStockDelivery` (Goods Received Note / GRN Form)",
    "- Controls: `cmbItems` (Populated with stock items), `txtQuantity`, `txtDeliveryRef` (Delivery Note #), `chkBulkMode` (Bulk delivery mode), `btnSaveDelivery`, `btnClose`.",
    "- Logic: Increases `Qty` in `Master_Stock`, records a `DELIVERY` row in `Movement_Log`, generates a Goods Received Note PDF in `Received_Items\\`, and autosaves workbook in `.xlsm` format.",
    "",
    "#### 4. `frmIssueRequest` (Departmental Requisition Cart Form)",
    "- Controls:",
    "  - Department section: `txtDeptID`, `btnLookupDept`, `lblDeptName`, `lblDeptHead`, `lblDeptEmail`.",
    "  - Item selection: `cmbItems` placed prominently at top of item section ('Click an item to select it') populated with active stock balances.",
    "  - Search filter: `txtSearch` search input bar placed directly BELOW dropdown list to filter items by code, keyword, or category.",
    "  - Quantity & Cart: `txtQty` with `-` / `+` numeric steppers, `btnAddItem` (Validates requested qty <= available in-stock qty), `lstQueue` (ListBox showing ItemID, ItemName, Category, Qty), `btnRemoveItem`, `btnClearCart`.",
    "  - Action button: `btnPreviewConfirm` — launches `frmPreviewConfirmation` passing cart data and department information.",
    "",
    "#### 5. `frmPreviewConfirmation` (Pre-Execution Review & Item Deletion Modal)",
    "- Controls: `lblDeptSummary` (Department ID, Name, Head, Issuer), `lstReviewItems` (ListBox showing all queued items), `btnDeleteItem` (Allows user to select and delete any item from the queue before proceeding), `btnConfirmExecute` (Executes stock deduction, audit logging, PDF export, and .xlsm autosave), `btnCancel` (Returns to issue form).",
    "- Logic: Ensures at least 1 item remains in queue. If user deletes all items, warns user and returns to cart.",
    "",
    "#### 6. `frmStockAdjustment` (Stock Count Discrepancy & Adjustment Form)",
    "- Controls: `cmbStockItem`, `lblSystemQty` (Displays current recorded balance), `txtPhysicalQty` (Input verified physical count), `lblVariance` (Dynamically shows `+` surplus or `-` deficit), `cmbReason` (Dropdown with standard discrepancy reasons), `txtCountRef` (Physical Audit Sheet #), `txtNotes` (Mandatory audit explanation), `btnSaveAdjustment`, `btnCancel`.",
    "- Logic: Validates non-negative physical count, updates `Master_Stock`, logs `ADJUSTMENT` in `Movement_Log`, generates `Stock_Adjustment_*.pdf` voucher into `Adjustments\\` folder.",
    "",
    "#### 7. `frmCreateStock` (Create New Inventory Item)",
    "- Controls: `txtItemID` (Auto-suggests next available ID, e.g. `ST-011`, `CL-111`, `GN-206`), `txtItemName`, `cmbCategory` ('Stationery', 'Cleaning', 'General'), `txtInitialQty`, `txtReorderLevel`, `cmbUnit` ('Reams', 'Boxes', 'Packs', 'Units', 'Containers', 'Drums', 'Rolls', 'Bottles', 'Cans', 'Kits'), `btnCreateItem`, `btnCancel`.",
    "- Logic: Validates unique ID, appends new row to `Master_Stock`, applies formatting, and logs creation.",
    "",
    "#### 8. `frmEditStockItem` (Edit / Rename Existing Item)",
    "- Controls: `cmbSelectStock`, `txtItemName`, `cmbCategory`, `txtQty`, `txtReorderLevel`, `cmbUnit`, `btnSave`, `btnCancel`.",
    "- Logic: Finds matching item row in `Master_Stock` and updates description, category, quantity, reorder level, and unit.",
    "",
    "#### 9. `frmDepartmentManager` (Manage Department Master Lookup)",
    "- Controls: `lstDepartments`, `txtDeptID`, `txtDeptName`, `txtDeptHeadName`, `txtDeptHeadEmail`, `btnAddDept`, `btnUpdateDept`, `btnDeleteDept`, `btnClose`.",
    "- Logic: Updates `Admin_Config!F:I` department directory table dynamically.",
    "",
    "#### 10. `frmUserManagement` (Rachel Pickard Superior Admin User CRUD)",
    "- Controls: `lstIssuers`, `txtIssuerID`, `txtIssuerName`, `txtRole`, `txtSecretPassword` (`PasswordChar = \"*\"`), `btnAdd`, `btnUpdate`, `btnDelete`, `btnClose`.",
    "- Logic: Accessible ONLY to Rachel Pickard (`ADM001`). Performs full CRUD on `Admin_Config!A:D` staff accounts table.",
    "",
    "---",
    "",
    "### 7. DOCUMENT RENDERING & AUTOMATED LOCAL PDF EXPORT SPECIFICATION",
    "When an Issue Requisition, Goods Received Delivery, or Stock Adjustment is confirmed, the system executes automated PDF voucher generation:",
    "",
    "#### A. Issue Slip Document Specifications:",
    "- Target Folder: `C:\\Stationery & Cleaning\\Issued_Items\\` (or active workbook directory subfolder).",
    "- File Naming Convention: `IssueSlip_{DeptID}_{Timestamp}.pdf`",
    "- Top-Left Official Logo: Insert the official organization logo ('PEX Green (2).png') in the top-left corner (height 28mm, width 16mm to fit header cell height legibly without distortion). Graphic features the lime-green RGB(198, 217, 44) striding worker and vertical 'paramount' typography on dark graphite canvas.",
    "- Layout & Structure:",
    "  - Top Header: 'PARAMOUNT PROCUREMENT & STORES DEPARTMENT' | 'STATIONERY & CLEANING ITEM ISSUE SLIP'",
    "  - Metadata Grid: Voucher Reference Number, Issue Timestamp, Target Department ID & Name, Department Head Name & Email, Authorized Issuer Name & ID, Storage Directory.",
    "  - Itemized Data Table: Item Code, Description, Category, Quantity Issued, Unit.",
    "  - Total Summary: Total line items and total units issued.",
    "  - Signature & Stamp Verification Box:",
    "    - Left Box: 'Issued By (Storekeeper Signature & Work ID)' with Digital Timestamp Signature: `YYYY-MM-DD HH:MM:SS-IssuerWorkID`.",
    "    - Right Box: 'Received By (Department Representative Signature & Date)'.",
    "- Export Routine: Uses a hidden temporary sheet, formats cells, applies borders, sets print area, and executes `wsTemp.ExportAsFixedFormat Type:=xlTypePDF, Filename:=sPdfPath, Quality:=xlQualityStandard`. Safely deletes `wsTemp` after export.",
    "",
    "#### B. Goods Received Note (GRN) Document Specifications:",
    "- Target Folder: `C:\\Stationery & Cleaning\\Received_Items\\`",
    "- File Naming Convention: `GRN_Voucher_{VoucherNumber}_{Timestamp}.pdf`",
    "- Top-Left Official Logo: Official PEX Green (2).png Logo attached as-is.",
    "- Structure: GRN Header, Delivery Reference Number, Supplier/Central Warehouse tag, Received Items table, Received Qty, Verified By signature box.",
    "",
    "#### C. Stock Adjustment Voucher Specifications:",
    "- Target Folder: `C:\\Stationery & Cleaning\\Adjustments\\`",
    "- File Naming Convention: `Stock_Adjustment_{VoucherNumber}_{Timestamp}.pdf`",
    "- Top-Left Official Logo: Official PEX Green (2).png Logo attached as-is.",
    "- Structure: Adjustment Header, Count Reference Number, Reason Code & Description, System vs Physical Count Table, Net Variance Calculation, Store Auditor & Superior Admin Approval Signatures.",
    "",
    "---",
    "",
    "### 8. REQUIRED STANDARD VBA MODULES & CODE STRUCTURE",
    "Provide complete, clean VBA code for the following modules:",
    "",
    "1. **`ThisWorkbook.cls` (Workbook Event Handlers)**:",
    "   - `Workbook_Open()`: Resets session variables, hides `Admin_Config` as `xlSheetVeryHidden`, validates directories via `EnsureDirectoriesExist()`, navigates to `Master_Stock`, and shows `frmLogin`.",
    "   - `Workbook_SheetActivate(ByVal Sh As Object)`: Intercepts clicks on `Admin_Config` and denies access unless `g_CurrentIssuerID = \"ADM001\"`.",
    "   - `Workbook_BeforeSave(ByVal SaveAsUI As Boolean, Cancel As Boolean)`: Enforces macro-enabled autosave (`SaveAs FileFormat 52`).",
    "",
    "2. **`mod_ThemeEngine.bas` (Light / Dark Theme Switching Engine)**:",
    "   - `ToggleWorkbookTheme()`: Toggles active theme between Light and Dark mode.",
    "   - `ApplyThemeToSheet(ws As Worksheet)`: Applies background, header, row, and border colors based on theme.",
    "   - `ApplyThemeToUserForm(frm As Object)`: Formats UserForm backgrounds, labels, textboxes, and command buttons.",
    "   - Color constants for all theme palette tokens.",
    "",
    "3. **`modProcurementSystem.bas` (Core Business & Stock Logic)**:",
    "   - `UpdateStockDelivery(...)`: Handles GRN additions, updates `Master_Stock`, appends to `Movement_Log`, generates GRN PDF.",
    "   - `ProcessIssueRequisition(...)`: Deducts stock from `Master_Stock`, appends `Movement_Log` entry, calls PDF generator, autosaves workbook.",
    "   - `ProcessStockAdjustment(...)`: Records physical count, recalculates variances, appends `Movement_Log` entry, generates adjustment PDF voucher.",
    "   - `EnsureDirectoriesExist()`: Creates `Issued_Items\\`, `Received_Items\\`, and `Adjustments\\` folders using `Dir()` and `MkDir`.",
    "   - `ExportRequisitionPDF(...)`, `ExportGRN_PDF(...)`, `ExportAdjustmentPDF(...)`: Builds voucher worksheet, inserts top-left brand logo, and exports to PDF via `ExportAsFixedFormat`.",
    "   - `SaveWorkbookAsXLSM()`: Calls `ThisWorkbook.SaveAs FileFormat:=52`.",
    "",
    "4. **`modSecurity.bas` (Session & Authentication Management)**:",
    "   - `ValidateIssuerLogin(workId As String, pass As String) As Boolean`: Verifies credentials against `Admin_Config!A:D`.",
    "   - Global session variables (`g_CurrentIssuerID`, `g_CurrentIssuerName`, `g_CurrentIssuerRole`, `g_IsAuthenticated`).",
    "   - `SetAdminConfigVisibility(visible As Boolean)`: Toggles `xlSheetVisible` vs `xlSheetVeryHidden`.",
    "",
    "5. **`mod_BackupRecovery.bas` (Automated Data Storage, Backup Schedule & Disaster Recovery - Superior Admin ADM001 Only)**:",
    "   - `CreateWorkbookSnapshot(backupType As String, description As String) As String`: Auto-generates timestamped snapshot `.xlsm.bak` in `C:\\Stationery & Cleaning\\Backups\\` (Hourly, Daily, or Transaction).",
    "   - `AutoBackupOnTransaction(txType As String, docRef As String)`: Triggers automatic background snapshot before and after critical stock transactions (RPO = 0 min).",
    "   - `ScheduleAutomatedBackups()`: Uses `Application.OnTime` to schedule automated background hourly differential snapshots alongside close-of-business Mon - Friday (16:30) full master backups.",
    "   - `RestoreSnapshotPointInTime(backupFilePath As String)`: Performs point-in-time disaster recovery with pre-restore safety snapshot (Strictly Rachel Pickard ADM001).",
    "   - `ExportEmergencyDataDump()`: Creates timestamped CSV data dumps of Master_Stock and Movement_Log for emergency offline access.",
    "   - `PruneOldBackups(retentionDays As Long)`: Automatically executes 30-day automated rolling retention pruning to prevent disk bloating.",
    "",
    "6. **`SetupMacro.bas` (One-Click Automated Project Generator)**:",
    "   - `CreateCompleteProcurementWorkbook()`: Programmatically creates all 3 sheets, builds initial stock items (Stationery `ST-001..`, Cleaning `CL-101..`, General `GN-201..`), initial movement logs, department directory, manager directory, staff accounts, and ribbon buttons with one click.",
    "",
    "7. **`Setup_XLSM_Project.ps1` (Automated PowerShell Build Script)**:",
    "   - Creates Excel COM Object, instantiates workbook, imports modules, populates data tables, configures conditional formatting, creates directories, and saves `.xlsm` workbook automatically.",
    "",
    "---",
    "",
    "### 9. VBA PROJECT PROTECTION & TRUST CENTER SECURITY",
    "- Instructions for locking the VBA project under **Tools > VBAProject Properties > Protection > Lock project for viewing** with a secure password.",
    "- Instructions for Excel **Trust Center > Macro Settings > Enable VBA macros** and adding the workbook folder to **Trusted Locations**.",
    "",
    "================================================================================",
    "END OF AI GENERATION PROMPT",
    "================================================================================"
  ].join("\n");
}

export function downloadAiMasterPromptFile(format: 'txt' | 'md' = 'md') {
  const content = generateAiMasterPrompt();
  const filename = format === 'md' ? 'AI_Master_Prompt_Excel_VBA_Procurement.md' : 'AI_Master_Prompt_Excel_VBA_Procurement.txt';
  const mimeType = format === 'md' ? 'text/markdown;charset=utf-8' : 'text/plain;charset=utf-8';

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
